name: build-test-deploy

on: push

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install
        run: npm install
      - name: npm build
        run: npm build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install
        run: npm install
      - name: npm build
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install
        run: npm install
      - name: npm build
        run: npm test
